import axios from 'axios';
const BACKEND_URL = 'https://my-restfulapi-reactnativeapp-default-rtdb.firebaseio.com/';

// Send amount, date , description , id is autogenerated by firebase
export function storeExpense(expenseData){
    //First part is the url to firebase and expenses.json is firebase expenses node 

    axios.post(`${BACKEND_URL}expenses.json`,
        expenseData
    );

}

export async function fetchExpenses(){
   const response = await axios.get(BACKEND_URL+'expenses.json');
   const expenses = [];
   for(const key in response.data){
    const expenseObj={
        id:key,
        amount: response.data[key].amount,
        date:new Date(response.data[key].date),
        descrription:response.data[key].description
    }
    expenses.push(expenseObj)
   }
   return expenses;
}