import axios from 'axios';

// Send amount, date , description , id is autogenerated by firebase
export function storeExpense(expenseData){
    //First part is the url to firebase and expenses.json is firebase expenses node 
    axios.post('https://my-restfulapi-reactnativeapp-default-rtdb.firebaseio.com/expenses.json',
        expenseData
    );

}